//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        users: {
            name: "users",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                secretField: {
                    name: "secretField",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.field("id")) }] }] as readonly AttributeApplication[]
                },
                testDate: {
                    name: "testDate",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                status: {
                    name: "status",
                    type: "String",
                    optional: true
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                profile: {
                    name: "profile",
                    type: "profiles",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("usersProfile") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("profileId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "user", name: "usersProfile", fields: ["profileId"], references: ["id"], onDelete: "SetNull" }
                },
                profileId: {
                    name: "profileId",
                    type: "String",
                    unique: true,
                    optional: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "profile"
                    ] as readonly string[]
                },
                referredBy: {
                    name: "referredBy",
                    type: "users",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("usersReferredBy") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("referredById")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "referrals", name: "usersReferredBy", fields: ["referredById"], references: ["id"], onDelete: "SetNull" }
                },
                referredById: {
                    name: "referredById",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "referredBy"
                    ] as readonly string[]
                },
                referrals: {
                    name: "referrals",
                    type: "users",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("usersReferredBy") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "referredBy", name: "usersReferredBy" }
                },
                posts: {
                    name: "posts",
                    type: "posts",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("postsAuthor") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "author", name: "postsAuthor" }
                },
                invitations: {
                    name: "invitations",
                    type: "invitations",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("invitationsInviter") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "inviter", name: "invitationsInviter" }
                },
                opponentInvitation: {
                    name: "opponentInvitation",
                    type: "invitations",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("invitationsOpponent") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "opponent", name: "invitationsOpponent" }
                },
                chessMatchs: {
                    name: "chessMatchs",
                    type: "chessMatchs",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("chessMatchsInviter") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "inviter", name: "chessMatchsInviter" }
                },
                skiMatchs: {
                    name: "skiMatchs",
                    type: "skiMatchs",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("skiMatchsInviter") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "inviter", name: "skiMatchsInviter" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read,create,delete") }, { name: "condition", value: ExpressionUtils.literal(true) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("update") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.field("id")) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                profileId: { type: "String" }
            }
        },
        profiles: {
            name: "profiles",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                bio: {
                    name: "bio",
                    type: "String",
                    optional: true
                },
                avatarUrl: {
                    name: "avatarUrl",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                user: {
                    name: "user",
                    type: "users",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("usersProfile") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "profile", name: "usersProfile" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        posts: {
            name: "posts",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                title: {
                    name: "title",
                    type: "String"
                },
                content: {
                    name: "content",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                author: {
                    name: "author",
                    type: "users",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("postsAuthor") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("authorId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "posts", name: "postsAuthor", fields: ["authorId"], references: ["id"], onDelete: "SetNull" }
                },
                authorId: {
                    name: "authorId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "author"
                    ] as readonly string[]
                },
                tags: {
                    name: "tags",
                    type: "tags",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("postsTags") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "posts", name: "postsTags" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        invitations: {
            name: "invitations",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                modelType: {
                    name: "modelType",
                    type: "String"
                },
                status: {
                    name: "status",
                    type: "String",
                    optional: true
                },
                timeControl: {
                    name: "timeControl",
                    type: "String",
                    optional: true
                },
                rated: {
                    name: "rated",
                    type: "Boolean",
                    optional: true
                },
                resort: {
                    name: "resort",
                    type: "String",
                    optional: true
                },
                skillLevel: {
                    name: "skillLevel",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                inviter: {
                    name: "inviter",
                    type: "users",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("invitationsInviter") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("inviterId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "invitations", name: "invitationsInviter", fields: ["inviterId"], references: ["id"], onDelete: "SetNull" }
                },
                inviterId: {
                    name: "inviterId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "inviter"
                    ] as readonly string[]
                },
                opponent: {
                    name: "opponent",
                    type: "users",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("invitationsOpponent") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("opponentId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "opponentInvitation", name: "invitationsOpponent", fields: ["opponentId"], references: ["id"], onDelete: "SetNull" }
                },
                opponentId: {
                    name: "opponentId",
                    type: "String",
                    unique: true,
                    optional: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "opponent"
                    ] as readonly string[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                opponentId: { type: "String" }
            }
        },
        chessMatchs: {
            name: "chessMatchs",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                timeControl: {
                    name: "timeControl",
                    type: "String"
                },
                rated: {
                    name: "rated",
                    type: "Boolean"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                inviter: {
                    name: "inviter",
                    type: "users",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("chessMatchsInviter") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("inviterId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "chessMatchs", name: "chessMatchsInviter", fields: ["inviterId"], references: ["id"], onDelete: "SetNull" }
                },
                inviterId: {
                    name: "inviterId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "inviter"
                    ] as readonly string[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        skiMatchs: {
            name: "skiMatchs",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                resort: {
                    name: "resort",
                    type: "String"
                },
                skillLevel: {
                    name: "skillLevel",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                inviter: {
                    name: "inviter",
                    type: "users",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("skiMatchsInviter") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("inviterId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "skiMatchs", name: "skiMatchsInviter", fields: ["inviterId"], references: ["id"], onDelete: "SetNull" }
                },
                inviterId: {
                    name: "inviterId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "inviter"
                    ] as readonly string[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        tags: {
            name: "tags",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                posts: {
                    name: "posts",
                    type: "posts",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("postsTags") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "tags", name: "postsTags" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        containers: {
            name: "containers",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                items: {
                    name: "items",
                    type: "items",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("containersItems") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "container", name: "containersItems" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        items: {
            name: "items",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                container: {
                    name: "container",
                    type: "containers",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("containersItems") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("containerId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "items", name: "containersItems", fields: ["containerId"], references: ["id"], onDelete: "SetNull" }
                },
                containerId: {
                    name: "containerId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "container"
                    ] as readonly string[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        listings: {
            name: "listings",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                priceAmount: {
                    name: "priceAmount",
                    type: "Float",
                    optional: true
                },
                priceCurrency: {
                    name: "priceCurrency",
                    type: "String",
                    optional: true
                },
                minBidAmount: {
                    name: "minBidAmount",
                    type: "Float",
                    optional: true
                },
                minBidCurrency: {
                    name: "minBidCurrency",
                    type: "String",
                    optional: true
                },
                slotStartHour: {
                    name: "slotStartHour",
                    type: "Float",
                    optional: true
                },
                slotStartMinute: {
                    name: "slotStartMinute",
                    type: "Float",
                    optional: true
                },
                slotEndHour: {
                    name: "slotEndHour",
                    type: "Float",
                    optional: true
                },
                slotEndMinute: {
                    name: "slotEndMinute",
                    type: "Float",
                    optional: true
                },
                flexPriceAmount: {
                    name: "flexPriceAmount",
                    type: "Float",
                    optional: true
                },
                flexPriceDiscount: {
                    name: "flexPriceDiscount",
                    type: "Float",
                    optional: true
                },
                tags: {
                    name: "tags",
                    type: "Json",
                    optional: true
                },
                schedule: {
                    name: "schedule",
                    type: "Json",
                    optional: true
                },
                slug: {
                    name: "slug",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        validatingListings: {
            name: "validatingListings",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                priceAmount: {
                    name: "priceAmount",
                    type: "Float",
                    optional: true
                },
                priceCurrency: {
                    name: "priceCurrency",
                    type: "String",
                    optional: true
                },
                slotStartHour: {
                    name: "slotStartHour",
                    type: "Float",
                    optional: true
                },
                slotStartMinute: {
                    name: "slotStartMinute",
                    type: "Float",
                    optional: true
                },
                slotEndHour: {
                    name: "slotEndHour",
                    type: "Float",
                    optional: true
                },
                slotEndMinute: {
                    name: "slotEndMinute",
                    type: "Float",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        remappedListings: {
            name: "remappedListings",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                priceCents: {
                    name: "priceCents",
                    type: "Float"
                },
                priceCurrency: {
                    name: "priceCurrency",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        appointments: {
            name: "appointments",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                scheduledFor: {
                    name: "scheduledFor",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                day: {
                    name: "day",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                startTime: {
                    name: "startTime",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                localStart: {
                    name: "localStart",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                billingMonth: {
                    name: "billingMonth",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                anniversary: {
                    name: "anniversary",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                zonedStartInstant: {
                    name: "zonedStartInstant",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                zonedStartZone: {
                    name: "zonedStartZone",
                    type: "String",
                    optional: true
                },
                duration: {
                    name: "duration",
                    type: "String",
                    optional: true
                },
                vacationFrom: {
                    name: "vacationFrom",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                vacationTo: {
                    name: "vacationTo",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        rooms: {
            name: "rooms",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                creatorId: {
                    name: "creatorId",
                    type: "String",
                    optional: true
                },
                inviteCode: {
                    name: "inviteCode",
                    type: "String",
                    attributes: [{ name: "@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.field("creatorId")) }] }] as readonly AttributeApplication[]
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                members: {
                    name: "members",
                    type: "roomMembers",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("roomMembers") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "room", name: "roomMembers" }
                },
                messages: {
                    name: "messages",
                    type: "roomMessages",
                    array: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("roomMessages") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "room", name: "roomMessages" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.field("members"), "?", ExpressionUtils.binary(ExpressionUtils.field("userId"), "==", ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]))) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("update") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.field("members"), "?", ExpressionUtils.binary(ExpressionUtils.field("userId"), "==", ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]))) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        roomMembers: {
            name: "roomMembers",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                userId: {
                    name: "userId",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                room: {
                    name: "room",
                    type: "rooms",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("roomMembers") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("roomId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "members", name: "roomMembers", fields: ["roomId"], references: ["id"], onDelete: "SetNull" }
                },
                roomId: {
                    name: "roomId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "room"
                    ] as readonly string[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.field("userId")) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        roomMessages: {
            name: "roomMessages",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                text: {
                    name: "text",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                room: {
                    name: "room",
                    type: "rooms",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("roomMessages") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("roomId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "messages", name: "roomMessages", fields: ["roomId"], references: ["id"], onDelete: "SetNull" }
                },
                roomId: {
                    name: "roomId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "room"
                    ] as readonly string[]
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("room"), ["creatorId"]), "==", ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"])) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create,update") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "!=", ExpressionUtils._null()) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        transactions: {
            name: "transactions",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                tick: {
                    name: "tick",
                    type: "Int",
                    unique: true,
                    optional: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                authorId: {
                    name: "authorId",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String"
                },
                reason: {
                    name: "reason",
                    type: "String",
                    optional: true
                },
                loggedAt: {
                    name: "loggedAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                changes: {
                    name: "changes",
                    type: "changes",
                    array: true,
                    relation: { opposite: "transaction" }
                }
            },
            attributes: [
                { name: "@@meta", args: [{ name: "name", value: ExpressionUtils.literal("sync") }, { name: "value", value: ExpressionUtils.literal("internal") }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                tick: { type: "Int" }
            }
        },
        changes: {
            name: "changes",
            fields: {
                transactionId: {
                    name: "transactionId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "transaction"
                    ] as readonly string[]
                },
                position: {
                    name: "position",
                    type: "Int",
                    id: true
                },
                kind: {
                    name: "kind",
                    type: "String"
                },
                entity: {
                    name: "entity",
                    type: "String"
                },
                entityId: {
                    name: "entityId",
                    type: "String"
                },
                field: {
                    name: "field",
                    type: "String",
                    optional: true
                },
                values: {
                    name: "values",
                    type: "Json",
                    optional: true
                },
                links: {
                    name: "links",
                    type: "Json",
                    optional: true
                },
                targetIds: {
                    name: "targetIds",
                    type: "Json",
                    optional: true
                },
                transaction: {
                    name: "transaction",
                    type: "transactions",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("transactionId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "changes", fields: ["transactionId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("transactionId"), ExpressionUtils.field("position")]) }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("entity"), ExpressionUtils.field("entityId")]) }] },
                { name: "@@meta", args: [{ name: "name", value: ExpressionUtils.literal("sync") }, { name: "value", value: ExpressionUtils.literal("internal") }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["transactionId", "position"],
            uniqueFields: {
                transactionId_position: { transactionId: { type: "String" }, position: { type: "Int" } }
            }
        },
        bucketLog: {
            name: "bucketLog",
            fields: {
                bucket: {
                    name: "bucket",
                    type: "String",
                    id: true
                },
                tick: {
                    name: "tick",
                    type: "Int",
                    id: true
                },
                entity: {
                    name: "entity",
                    type: "String",
                    id: true
                },
                entityId: {
                    name: "entityId",
                    type: "String",
                    id: true
                },
                removed: {
                    name: "removed",
                    type: "Boolean"
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("bucket"), ExpressionUtils.field("tick"), ExpressionUtils.field("entity"), ExpressionUtils.field("entityId")]) }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("entity"), ExpressionUtils.field("tick")]) }] },
                { name: "@@meta", args: [{ name: "name", value: ExpressionUtils.literal("sync") }, { name: "value", value: ExpressionUtils.literal("internal") }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["bucket", "tick", "entity", "entityId"],
            uniqueFields: {
                bucket_tick_entity_entityId: { bucket: { type: "String" }, tick: { type: "Int" }, entity: { type: "String" }, entityId: { type: "String" } }
            }
        },
        changeFeedPosition: {
            name: "changeFeedPosition",
            fields: {
                slot: {
                    name: "slot",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                lsn: {
                    name: "lsn",
                    type: "String"
                }
            },
            attributes: [
                { name: "@@meta", args: [{ name: "name", value: ExpressionUtils.literal("sync") }, { name: "value", value: ExpressionUtils.literal("internal") }] }
            ] as readonly AttributeApplication[],
            idFields: ["slot"],
            uniqueFields: {
                slot: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Auth: {
            name: "Auth",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@auth" }
            ] as readonly AttributeApplication[]
        }
    } as const;
    authType = "Auth" as const;
    plugins = {};
}
export const schema = new SchemaType();
